### PlantAdd(관리 식물 등록)
POST http://localhost:8080/plant/add
Content-Type: application/json

{
  "nickName": "행복이",
  "plantName": "해피트리",
  "firstDate": "2203-10-14",
  "userId": 6
}

### PlantUpdate(관리 식물 편집)
POST http://localhost:8080/plant/update
Content-Type: application/json

{
  "firstDate": "2203-10-18",
  "plantId": 1
}

### PlantDelete(관리 식물 삭제)
POST http://localhost:8080/plant/delete
Content-Type: application/json

{
  "plantId": 2
}

### GET 식물 조회
GET http://localhost:8080/plant/3
Accept: application/json

### GET 식물리스트 조회
GET http://localhost:8080/plant/list/6
Accept: application/json

